kind: ConfigMap
apiVersion: v1
metadata:
  name: disco-yumemi
data:
  bot.yml: |-
    name: Yumemi
    services:
      - load: discord
        jobs:
          - load: discourse
            url: https://forum.kazamatsuri.org
          - load: verification
            channel: access-requests
            grant: Dangos
            discourse:
              url: https://forum.kazamatsuri.org
              topic_id: 2000
              trust_level: 2
            lines:
              success: "Your identity has been verified, welcome!"
              name_not_in_post: "Hm, it doesn't appear as though you have mentioned your Discord username in your forum post... perhaps you did not spell it correctly?"
              level_too_low: "I'm sorry, but I cannot let you in until you have reached the 'Dango' trust level. To raise your trust level, please participate on the forum for a few days, and it should come naturally. You may confirm your trust level on your forum user page at any time."
              error: "I apologize, but I am unable to verify you... there appears to be something wrong... um, please try again!"
          - load: conversion
            lines:
              currency: "%s would be... %s. Do note that my sources only update once per day, so this may be a little bit old."
              currency_multi: "%s would be $%s, €%s, £%s or ¥%s. Do note that my sources only update once per day, so this may be a little bit old."
      # - load: discourse
      #   url: https://forum.kazamatsuri.org
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: disco-yumemi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disco-yumemi
  template:
    metadata:
      name: disco-yumemi
      labels:
        app: disco-yumemi
    spec:
      containers:
      - name: disco
        image: kazokuco/disco:v1
        args: [run, /etc/disco/bot.yml]
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: disco-yumemi
                key: discord.token
        volumeMounts:
        - name: config-volume
          mountPath: /etc/disco
      volumes:
      - name: config-volume
        configMap:
          name: disco-yumemi
