apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8086
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.2.1
        ports:
        - name: http
          containerPort: 8086
        - name: admin
          containerPort: 8083
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb
      volumes:
      - name: data
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: influxdb
