apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-lb
data:
  body-size: 10m
  proxy-read-timeout: '31536000'
  proxy-send-timeout: '31536000'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress-lb
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-lb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --nginx-configmap=$(POD_NAMESPACE)/nginx-ingress-lb
