apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  # type: NodePort
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    # nodePort: 32637
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.6
        args: [
          redis-server,
          --appendonly, 'yes',
          --save, '60', '1000',
        ]
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis
