apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  # type: NodePort
  ports:
  - name: redis
    port: 6379
    # nodePort: 32637
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.6
        args: [
          redis-server,
          --appendonly, 'yes',
          --save, '60', '1000',
        ]
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: redis-exporter
  ports:
  - name: scrape
    port: 9121
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        imagePullPolicy: Always
        args:
        - -redis.addr=redis.default.svc.cluster.local:6379
        ports:
        - name: scrape
          containerPort: 9121
        livenessProbe:
          httpGet:
            path: /
            port: scrape
