apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana.kazoku.co
spec:
  rules:
  - host: grafana.kazoku.co
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
