apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kazamatsuri.org
spec:
  rules:
  - host: kazamatsuri.org
    http:
      paths:
      - backend:
          serviceName: ghost-kazamatsuri
          servicePort: 80
  - host: forum.kazamatsuri.org
    http:
      paths:
      - backend:
          serviceName: discourse
          servicePort: 80
  - host: new.kazamatsuri.org
    http:
      paths:
      - backend:
          serviceName: kakera
          servicePort: 80
