apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kazoku.co
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: kazoku.co-tls
    hosts:
    - kazoku.co
    - sandbox.kazoku.co
    - grafana.kazoku.co
    - hooks.kazoku.co
  rules:
  - host: kazoku.co
    http:
      paths:
      - backend:
          serviceName: default-http-backend
          servicePort: 80
  - host: sandbox.kazoku.co
    http:
      paths:
      - backend:
          serviceName: discourse
          servicePort: 80
  - host: grafana.kazoku.co
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
  - host: hooks.kazoku.co
    http:
      paths:
      - backend:
          serviceName: grappler
          servicePort: 80
