apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rokkenjima.org
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: rokkenjima.org-tls
    hosts:
    - rokkenjima.org
    - forum.rokkenjima.org
    - old.rokkenjima.org
  rules:
  - host: rokkenjima.org
    http:
      paths:
      - backend:
          serviceName: kakera
          servicePort: 80
  - host: old.rokkenjima.org
    http:
      paths:
      - backend:
          serviceName: ghost-rokkenjima
          servicePort: 80
  - host: forum.rokkenjima.org
    http:
      paths:
      - backend:
          serviceName: discourse
          servicePort: 80
